export const Types = {
  ADD_TASK: 'ADD_TASK',
  TOGGLE_TASK_COMPLETED: 'TOGGLE_TASK_COMPLETED',
  DELETE_ALL_TASKS: 'DELETE_ALL_TASKS',
  DELETE_TASK: 'DELETE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  SET_EDIT_TASK: 'SET_EDIT_TASK',
};
