export const Types = {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',
  GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
};
